### PR TITLE
Only send 3 gratuitous ARP packets after switching to ACTIVATED state

### LINKED ISSUE #79: fail to announce our IP: no buffer space available - Fail to ensure IP
View details in Rollbar: [https://rollbar.com/Scalingo/link/items/12/](https://rollbar.com/Scalingo/link/items/12/)

```
Traceback (most recent call last):

logrus_rollbar.wrappedError: fail to announce our IP: no buffer space available - Fail to ensure IPTraceback (most recent call last):

errors.withStack: fail to announce our IP: no buffer space available
```

### PR DESCRIPTION
**Pull request by Soulou**
gARP goal is to enfore a change of ARP tables in the infrastructure after a failover happens,
when the ACTIVATED node for an IP is changing. Thus it should not be sent continously but only
when a change happen.

That's what is describe here

https://www.practicalnetworking.net/series/arp/gratuitous-arp/

And applied in the VRRP protocol for instance

https://tools.ietf.org/html/rfc3768

Thus we're now only sending them at that moment, and then servers will answer normal ARPs requests afterwards, the three gARP should be enough to trigger the table update everywhere, it's what is done by keepalived

Fixes #79

The issue is fixed because it was related to the point that the service was sending continously too many gARP at the same time, now the number of gARP has been decreased
and some randomization has been added to avoid all gARPs to be sent at the same time

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -1,30 +1,57 @@
...
+const DefaultDelta Delta = 0.25
+
+// PlusMinusDelta returns a number [value - value * delta ≤ value ≤ value + value * delta]
+func PlusMinusDelta(value float64, delta Delta) float64 {
+	lower := float64(value) * (1.0 - float64(delta))
+	higher := float64(value) * (1.0 + float64(delta))
+	diff := higher - lower
+	rate := rand.Float64()
+	return lower + rate*diff
+}
```
Comment (johnsudaar) [inline config/config.go]: This is reallly complicated.

Why not something simpler like:

```
func RandomDurationAround(duration time.Duration, scatteringPercentage float64) time.Duration {
	delta := int64(float64(duration) * 2 * scatteringPercentage)
	return time.Duration(int64(duration) + rand.Int63n(delta) - (delta / 2))
}
```
