### PR TITLE
Do not accept a port of 0 for new IP health checks

### LINKED ISSUE #92: Do not accept a port of 0 for healthcheck
LinK should not accept we create a healthcheck with a port of `0`

View details in Rollbar: [https://rollbar.com/Scalingo/link/items/1/](https://rollbar.com/Scalingo/link/items/1/)

```
Traceback (most recent call last):

logrus_rollbar.wrappedError: prober error: probe tcp: probe check failed: fail to open TCP connection: dial tcp 10.1.0.103:0: connect: connection refused - healthcheck failedTraceback (most recent call last):

prober.ProberError: prober error: probe tcp: probe check failed: fail to open TCP connection: dial tcp 10.1.0.103:0: connect: connection refused
```

### PR DESCRIPTION
**Pull request by EtienneM**
Fix #92

### CODE REVIEW

File: web/ip_controller.go [hunk 1]
```diff
@@ -84,6 +85,13 @@ func (c ipController) Create(w http.ResponseWriter, r *http.Request, p map[strin
 		w.Write([]byte(`{"msg": "invalid IP"}`))
 		return nil
 	}
+	for _, check := range ip.Checks {
+		if check.Port == 0 {
```
Comment (johnsudaar) [inline web/ip_controller.go:89]: While you're at it could you also check it's < 65534 ?
